fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,10 +25,26 @@ jobs:
       - name: Get the latest version from DockerHub
         id: get-latest-version
         run: |
-          LATEST_VERSION=$(curl -s https://hub.docker.com/v2/repositories/ym5533/blogfrontend/tags | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1)
+          # Authenticate to Docker Hub and get the token
+          TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
+            -d "{\"username\": \"${{ secrets.DOCKER_USERNAME }}\", \"password\": \"${{ secrets.DOCKER_PASSWORD }}\"}" \
+            https://hub.docker.com/v2/users/login/ | jq -r .token)
+
+          # Check if token was obtained
+          if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
+            echo "Failed to authenticate. Please check your username and password."
+            exit 1
+          fi
+
+          # Fetch tags for the private repository
+          LATEST_VERSION=$(curl -s -H "Authorization: Bearer $TOKEN" \
+            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/blogfrontend/tags/" | \
+            jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1)
+
           if [ -z "$LATEST_VERSION" ]; then
             LATEST_VERSION="0.0.0"  # Default to 0.0.0 if no versions exist
           fi
+
           echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
 
       - name: Increment the patch version
